---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: percepto
  labels:
    type: percepto
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/zohran-tuf/Desktop/code/percepto/percepto-be/serve/k8s
    server: 192.168.0.56