apiVersion: v1
kind: Pod
metadata:
  name: orch
  namespace: default
  labels:
    name: orch
spec:
  serviceAccountName: orch-service
  restartPolicy: Never
  containers:
  - name: orch
    image: zafeeruddin/orch
    securityContext:
        capabilities:
          add:
            - NET_RAW
            - NET_ADMIN
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    resources:
      limits:
        memory: "512Mi"
        cpu: "1024m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orch-service
  namespace: default
---
# Changed to ClusterRole to allow cross-namespace access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orch-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["create", "watch", "get", "list", "delete"]
---
# Changed to ClusterRoleBinding for cross-namespace access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orch-rolebinding
subjects:
- kind: ServiceAccount
  name: orch-service  # Fixed to match the service account name
  namespace: default
roleRef:
  kind: ClusterRole
  name: orch-role
  apiGroup: rbac.authorization.k8s.io