---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logger
  namespace: default  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logger-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["create", "watch", "get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logger-rolebinding
subjects:
- kind: ServiceAccount
  name: logger
  namespace: default
roleRef:
  kind: ClusterRole
  name: orch-role
  apiGroup: rbac.authorization.k8s.io