apiVersion: v1
kind: Pod
metadata:
  name: train-pod
  labels:
    name: train-pod
spec:
  containers:
  - name: train-pod
    image: zafeeruddin/train
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /var
      name: nfs-storage
  nodeSelector:
    disktype: highgpu
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: redis-pvc
  restartPolicy: Never
  tolerations:
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"
