apiVersion: apps/v1
kind: Deployment
metadata:
  name: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status
  template:
    metadata:
      labels:
        app: status
    spec:
      hostNetwork: true
      serviceAccountName: status-service  
      containers:
      - name: status
        image: zafeeruddin/status
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        